workflows:
  android-release:
    name: Code Magic - Android Release
    max_build_duration: 60
    environment:
      flutter: stable
      android_signing:
        - keystore_reference
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release \
            --build-name=1.0.0 \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - ridergeming170@gmail.com
        notify:
          success: true
          failure: true
